name:  Nueva titulaci贸n
description: Solicita a帽adir soporte para una nueva titulaci贸n de la EPS
title: "[Titulaci贸n]: "
labels: ["titulaci贸n", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por ayudar a ampliar el soporte de titulaciones! 
        Por favor, proporciona la informaci贸n necesaria para a帽adir tu titulaci贸n.

  - type: input
    id: name
    attributes:
      label: Nombre completo de la titulaci贸n
      description: El nombre oficial tal como aparece en la EPS
      placeholder: "Grado en Ingenier铆a de Ejemplo"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Tipo de titulaci贸n
      options:
        - Grado
        - M谩ster Universitario
    validations:
      required: true

  - type: input
    id: color
    attributes:
      label: Color corporativo
      description: El color que identifica a la titulaci贸n (c贸digo hexadecimal o nombre)
      placeholder: "#1a5276 o Azul oscuro"
    validations:
      required: true

  - type: textarea
    id: logos
    attributes:
      label: Logos de la titulaci贸n
      description: |
        驴Tienes acceso a los logos oficiales de la titulaci贸n?
        Idealmente necesitamos:
        - Logo en fondo de color (para portada a color)
        - Logo en fondo blanco (para portada B/N)
        
        Puedes adjuntar archivos o proporcionar enlaces.
        Formatos preferidos: PDF, SVG, PNG de alta resoluci贸n
      placeholder: "Adjunto los logos... / Los logos se pueden encontrar en..."
    validations:
      required: true

  - type: input
    id: department
    attributes:
      label: Departamento principal
      description: El departamento m谩s relacionado con esta titulaci贸n (opcional)
      placeholder: "Departamento de Tecnolog铆a Inform谩tica y Computaci贸n"
    validations:
      required: false

  - type: input
    id: website
    attributes:
      label: Web de la titulaci贸n
      description: Enlace a la p谩gina oficial de la titulaci贸n en la EPS
      placeholder: "https://eps.ua.es/es/..."
    validations:
      required: false

  - type: textarea
    id: style-guide
    attributes:
      label: Gu铆a de estilo
      description: |
        驴Existe alguna gu铆a de estilo espec铆fica para esta titulaci贸n?
        Si es diferente a la gu铆a general de la EPS, ind铆calo aqu铆.
      placeholder: "La titulaci贸n tiene requisitos espec铆ficos como..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: 驴Puedes proporcionar m谩s informaci贸n?
      options:
        - label: Puedo proporcionar los archivos de logo en formato vectorial (PDF/SVG)
        - label: Puedo verificar que el dise帽o final es correcto seg煤n las normas de la titulaci贸n
        - label: Conozco a alguien que pueda validar el dise帽o (profesor, coordinador, etc.)

  - type: textarea
    id: additional
    attributes:
      label: Informaci贸n adicional
      description: Cualquier otro detalle relevante
      placeholder: "El logo tiene variantes para... / Hay que tener en cuenta..."
